node {
	docker.image('node:lts-bullseye-slim').inside('-p 3000:3000' ) {
		withEnv(['CI="true"']) {
			stage('Build') { 
				echo "Hilmatrix scripted Jenkinsfile - Build"
				sh 'npm install' 
			}
			stage('Test') {
				echo "Hilmatrix scripted Jenkinsfile - Test"
				sh './jenkins/scripts/test.sh'
			}
			stage('Deliver') {
				echo "Hilmatrix scripted Jenkinsfile - Deliver"
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
		}
    }
}
