node {
	docker.image('node:lts-bullseye-slim').inside('-p 3000:3000' ) {
		withEnv(['CI="true"']) {
			stage('Build') { 
				sh 'npm install' 
			}
			stage('Test') {
				sh './jenkins/scripts/test.sh'
			}
			stage('Approval') {
				input message: 'Lanjutkan ke tahap Deploy ?' 
			}
			stage('Deliver') {
				sh './jenkins/scripts/deliver.sh'
				sh 'sleep 1m'
				sh './jenkins/scripts/kill.sh'
			}
		}
    }
}
